#!/usr/bin/env ruby -w
# voip_test.exp
# Author: Andy Bettisworth
# Description: Automate the testing of Voice Over IP networks


## TESTS of performance

# ICMP or ping test for each phone - to establish KPIs, including latency, jitter, packet loss, and MOS score
# IP SLA tests - to get an understanding of the health of the paths, capturing voice specific data and what should be expected from a latency, jitter, packet loss and MOS score
# Qualities of Service (QoS) tests - to look for errors, drops, and interface utilization, and understand how many QoS queues are configured
# Network Traffic Assessment - to determine how calls are routed through the system
